### ISSUE TITLE
avinetworks.avisdk vs vmware.alb

### ISSUE THREAD

**Issue by Rob-Wal** [avinetworks/ansible-collection-alb#145]
### Is your feature request related to a problem? Please describe.

Not related to a problem.  Seeking better guidance for my self and future alb automators.

### Describe the solution you'd like

New to AVI/NSX-ALB automation.  Some recommendation/guidelines in the README on the difference between avinetworks.avisdk vs vmware.alb would be helpful.  

I understand the difference between a roles and collections.

If using the latest NSX-ALB controller (22.1.2) what the recommended ansible setup?

Are there any functional difference?
Any compatibility issues using the avinetworks.avisdk vs vmware.alb?
Any ALB requirements?

**Comment by chaitanyaavi** [comment]
No Functional difference we have stopped maintaining avinetworks.avisdk for future releases so its recommended to move to vmware.alb.
