### ISSUE TITLE
Idempotence test failed for avi_virtualservice

### ISSUE THREAD

**Issue by patcoq** [avinetworks/ansible-collection-alb#86]
### Describe the bug

Ran the avi_virtualservice module with exact same parameters without changing anything. Result is a failure because the virtual service already exists.
Same behavior with 21.1.3 and 21.1.4 module version.
ALB controller is running 21.1.3 version

ran 
- name: Configure tcp {{ vs_item.name }} Virtual Server
  vmware.alb.avi_virtualservice:
    avi_credentials: "{{ avi_credentials }}"
    name: "{{ vs_item.name }}"
    description: "{{ vs_item.description | default(omit) }}"
    state: present
    vsvip_ref: "/api/vsvip/?name={{ vs_item.name }}_vip"
    services: "{{ services_list }}"
    application_profile_ref: "/api/applicationprofile?name={{ vs_item.application_profile }}"
    pool_ref: "/api/pool?name={{ vs_item.name }}_pool"
    cloud_ref:  "/api/cloud/?name={{ cloud_name.obj.name }}"
    use_vip_as_snat: true
    se_group_ref: "/api/serviceenginegroup/?name={{ vs_item.se_group }}"
  when: "'tcp' in vs_item.application_profile
  

### Reproduction steps

```bash
ran 
- name: Configure tcp {{ vs_item.name }} Virtual Server
  vmware.alb.avi_virtualservice:
    avi_credentials: "{{ avi_credentials }}"
    name: "{{ vs_item.name }}"
    description: "{{ vs_item.description | default(omit) }}"
    state: present
    vsvip_ref: "/api/vsvip/?name={{ vs_item.name }}_vip"
    services: "{{ services_list }}"
    application_profile_ref: "/api/applicationprofile?name={{ vs_item.application_profile }}"
    pool_ref: "/api/pool?name={{ vs_item.name }}_pool"
    cloud_ref:  "/api/cloud/?name={{ cloud_name.obj.name }}"
    use_vip_as_snat: true
    se_group_ref: "/api/serviceenginegroup/?name={{ vs_item.se_group }}"
  when: "'tcp' in vs_item.application_profile

Create the object the 1st time.
Fails with the following message when we run it afterwards.
fatal: [xxxxxxxxx]: FAILED! => {"changed": false, "msg": "Error 409 Msg {\"error\": \"Error in creating VirtualService xxxxxxxxxxx : Virtual service with this Name, Tenant ref and Cloud ref already exists.\"} ........
```

### Expected behavior

With the state:present parameter, the task should do nothing if the object already exists on the controller.

**Comment by chandanapatnala** [comment]
Error was not reproducible. 
Tested on:-
ansible =2.9.13
python version = 3.8.12
Controller version=21.1.3
